### ISSUE TITLE
Precent Width Issue

### ISSUE THREAD

**Issue by beegmon** [ctubio/tribeca#103]
I am glad to see #96 go in!

However, the percentage width, as it is now, presents a different challenge. Over the last month or two I have identified several profitable widths to quote at. With percentage widths I no longer have the ability to set a static width when percentage is enabled. Instead it floats with fair value +/- percent of fair value. This means I am consistently checking the width% to the fair value to see if it is still within my one of identified profitable.

As BTC price goes up or down by medium to large amounts the %width must be updated to keep triebca in one of the width ranges I have found to be profitable.

Would it be possible to make percentage width enabled/disabled separately overall? This way I can use percentages for TBP, PDiv, size, but not for width which is would still be set statically.

Or, what I think might be better, is allow static width settings with the addition of a percentage which is added/subtracted to a bid/ask when quoting. This way you can still account for a fee, while staying in your generally profitable width range overall.

**Comment by ctubio** [comment]
im in ther same situation as you, will support % width out of main %
