### ISSUE TITLE
Very long installation ? (Question)

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#108]
Hello Carles,

Why is the new installation so long?

I'm struggling to do updates now haha.

Thanks for your answer

**Comment by ctubio** [comment]
yep, see https://github.com/ctubio/tribeca/issues/74

now we have more lovely deps (http://www.quickfixengine.org/)

let me know if you have any problems, it should work eaSy (10min compilation) in new aws ec2 instances with fresh debian/centos image (like this https://travis-ci.org/ctubio/tribeca/jobs/236881063)

**Comment by ctubio** [comment]
also is only the first install, once you have /usr/local/include/quickfix/* files it will not run again so long

**Comment by Camille92** [comment]
Good! So it means that we're connected to Coinbase with FIX now ?

**Comment by ctubio** [comment]
still using https calls, but we have all tools installed and ready to make use of FIX protocol if we ever understand how it works xD

**Comment by Camille92** [comment]
Okay, I get blocked here in one instance  I don't know what happens.

In file included from C++/fix40/Message.h:4:0,
                 from C++/fix40/TestRequest.h:4,
                 from C++/test/DataDictionaryTestCase.cpp:30,
                 from ut.cpp:30:
C++/fix40/../Message.h:342:15: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   static std::auto_ptr<DataDictionary> s_dataDictionary;
               ^
In file included from /usr/include/c++/5/memory:81:0,
                 from C++/Utility.h:99,
                 from ut.cpp:27:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;

**Comment by ctubio** [comment]
can you copy the full log?

**Comment by Camille92** [comment]
Well that's very long so here is a pastbin.

I think the end is the interesting part.

I stop the process after it stays like that for over 10mn

https://pastebin.com/CstkKH99

**Comment by ctubio** [comment]
just don't stop it :dancer: you are arround https://travis-ci.org/ctubio/tribeca/jobs/236908873#L2630

**Comment by Camille92** [comment]
... Well, you right just added to wait a bit more.

Sorry!

**Comment by ctubio** [comment]
nice'¡ :beers:
