### ISSUE TITLE
Make ewmaLong and ewmaShort customizable (maaaybe ewmaProtection too)

### ISSUE THREAD

**Issue by ctubio** [ctubio/tribeca#114]
:dancer:

**Comment by ctubio** [comment]
so to make them customizable, the plan is to leave all math equal, just allow to play with the interval in X minutes

**Comment by Camille92** [comment]
Hey Carles,

I think it's a great idea, but I would say if you want to make it customizable, better being able to play with those 3 factors:

1) Length of Ewmalong
2) Length of Ewmashort
3) Sensibility of TBP evolution (the *5 here https://github.com/ctubio/tribeca/blob/master/src/server/position-management.ts#L81

The interval is only the update interval, or how often tribeca is going to actualize TBP and as now we have the ewma saved on reboot, I would say the shorter the better (but why not more customization). :D

**Comment by ctubio** [comment]
thanks and sorry for my dummy initial approach xD

**Comment by ctubio** [comment]
see https://github.com/ctubio/tribeca/issues/115#issuecomment-305270671 before do nothing

**Comment by ctubio** [comment]
ok only missing the make use of medium ewma (is not used anywhere yet) and to allow a customizable sensibility

closing this because will be done together with #115
