### ISSUE TITLE
[Feature Request] Buy & Hold and Sell & Hold

### ISSUE THREAD

**Issue by jangrewe** [ctubio/tribeca#116]
I've noticed that there are moments where i'd really like to just hit a button that places on final order to i.e. buy as much BTC as possible at the current price and then hold until manually "unpaused", and vice versa.
Sometimes the market just seems to be unfavorable to regular trades, resulting in missed opportunities compared to just buy & hold or sell & hold - if you watch the market closely.

I was also thinking that the "Release Quotes" button (the big red/green one) would start/stop sending orders, but that currently doesn't seem to be the case - at least not for me, running in auto mode.

**Comment by ctubio** [comment]
for me the start/stop button never failed, if this happens to you always, can you maybe send a video or something? in case it happens eventually, maybe you know the steps to reproduce it?

thanks'¡

**Comment by ctubio** [comment]
about the hold & sell feature, doesnt work for you if you set pingAt to some side and Maual apr to another side? also StopPings with or without Clean All Pings can be conbined to do somewhat similar, no? (also make use of maxBid/AskSize checkboxes)

**Comment by jangrewe** [comment]
uhm, nevermind the start/stop issue, i think i had a orphaned instance running, which was still sending orders. 
this also seemed to be causing the "seemingly static" profit display, as that's working fine now that i killed all processes.

I haven't looked into what would be the best settings to accomplish a Buy/Sell & Hold, but i was thinking about a simple button for each, like an emergency "dump and stop trading" switch ;-)

**Comment by ctubio** [comment]
really, i noticed that what i do to sell/buy and hold is set LongPingAggressive at pongAt until all ina side is sold, because it drains a side quick quick if the opposite side have pings
