### ISSUE TITLE
Docker run - Error

### ISSUE THREAD

**Issue by Daniel-Rafique** [ctubio/tribeca#117]
When running:

`docker run -p 3000:3000 --link tribeca-mongo:mongo --name tribeca -d tribeca`

The following error even with `sudo`

docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"node_modules/.bin/forever\\\": stat node_modules/.bin/forever: no such file or directory\"\n".

The directory & file that is referenced is present under node_modules/.bin/forever

**Comment by ctubio** [comment]
thanks for the report'¡
