### ISSUE TITLE
Bitfinex bot not showing Wallet in UI

### ISSUE THREAD

**Issue by b-seite** [ctubio/tribeca#128]
Hi, 

i tried to set up a Bitfinex bot. Everything went well except that on the UI the wallet is gone and the bot will not send any quotes. (see Screenshot below)
Even the Trading button gets green when it is pressed.

The console started with node says that: 

> 08:22:36.877 main Requiring authentication to web client
08:22:36.903 main Listening to admins on *: 3000
08:22:37.398 bitfinex Starting nonce: 1496996557398
08:22:37.412 main Exchange details { exchange: 'Bitfinex',
  pair: 'BTC/USD',
  minTick: 0.1,
  minSize: 0.01,
  makeFee: 0.001,
  takeFee: 0.002,
  hasSelfTradePrevention: false }
08:22:37.597 bitfinex Bitfinex info: { event: 'info', version: 2 }
08:22:37.751 bitfinex Successfully connected to trades
08:22:37.753 bitfinex Authentication status: OK
08:22:37.782 bitfinex Successfully connected to book
08:32:29.513 active Changed saved quoting state to true
08:32:29.513 active Changed quoting mode to true

Any ideas?

Kind regards Boris
---
```
app exchange: Bitfinex/BTC/USD
app version: latest
```
![bildschirmfoto 2017-06-09 um 10 31 50](https://user-images.githubusercontent.com/540850/26967742-af328b44-4cff-11e7-8db4-f2811d00c898.png)

**Comment by Camille92** [comment]
I can see two options, either it is like what I've been experiencing in #122 or you did not give enough permissions to the API when you created it.

Please check your API preferences and send some more logs :)

**Comment by ctubio** [comment]
my api permissions looks like:
![api](https://user-images.githubusercontent.com/1634027/26987265-311c26ba-4d4b-11e7-9404-075526a57cff.png)

also try to login to the website of bitfinex, sometimes there is a new user agreement that you need to accept in order to continue using the bitfinex service

**Comment by ekienmeier** [comment]
I have the exact same problem - wallet info stays empty, log is basically the same (no errors). I tried other pairs (ETH/BTC), no success. Changing API key permissions didn't help either. Maybe it has something to do with pending account verification?

**Comment by ctubio** [comment]
i think so, do you have any user agreement pending to accept if you login into website of bitfinex? (should be a popup at the very next screen after login)

**Comment by b-seite** [comment]
Ah ok, that could be the Point. 
I now do the complete verification process on bitfenix and then i will see if the behaviour is gone.

**Comment by ekienmeier** [comment]
Verification didn't fix it for me, wallet info was still not showing. I created a "Tether" exchange wallet and now everything seems to work.

**Comment by zbanga** [comment]
@ekienmeier what is a tether exchange wallet?

**Comment by ctubio** [comment]
https://www.bitfinex.com/posts/31

**Comment by ekienmeier** [comment]
@zbanga I think I read somewhere that on Bitfinex you're not really trading BTC for USD, but for USDT (USD Tether). In order for Tribeca / K to work with this "currency", you need to add an exchange wallet for USDT.

Login to the Bitfinex website, menu "Transfer" -> Deposit. From the list of currencies, select "Tether" (at the bottom) and create an exchange wallet.

After performing these steps, my wallet info was shown and Tribeca / K was able to perform trades.

Hope this helps!

**Comment by zbanga** [comment]
@ekienmeier @ctubio Thanks for the tips and the help! However, I'm not really trading any usd at the moment. I'm trading eth/btc but tribeca does not show up for me. I've put in a verification request a week ago and now waiting to see if getting verified fixes the problem. I'll let everyone know if this fixes it.
