### ISSUE TITLE
(IMPROVEMENT) APR + PingAggressive 

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#18]
I was thinking the other day that this two settings should be linked.

Ie: When APR is activated, it should be done in PingAggresive mode!

The goal of APR is to get the position rebalanced ASAP, being in PingAggressive mode should help to that.

Maybe it should be enabled by default, maybe as a option but I think it's a good idea.

Tell me what you think,

Camille

**Comment by ctubio** [comment]
niiice'¡
will add it as a default and with a comment in the MANUAL of apr/pongAt.

if nobody disagrees, will only have effect if apr is ON, respecting the Long or Short ping option, but enforcing Aggressive instead of Fair ping in pongAt option.

**Comment by Camille92** [comment]
It is exactly that ;)

The expected benefit is to be able to have a wider width setting during normal time without being afraid to miss on a mouvement / being blocked with BTC during a price evolution :)

**Comment by ctubio** [comment]
![tumblr_koizo9aq7l1qzjombo1_400](https://cloud.githubusercontent.com/assets/1634027/22693171/69484b22-ed42-11e6-93d0-bc28817d709e.jpg)

**Comment by Camille92** [comment]
Unfortunately, after some testing this setting is way too hardcore, at least for me.

What happens is that basically I have a huge (because of APR) buy or sell order created right at the best bid/ask and most of the time results in a negative trade.

I give you an example of what happens usually:
I'm in normal mode, quoting both side.

A sell order match my bid and move the market a little bit down.

Since I bought tribeca, I go outside of pdiv and switch to APR sell mode.
Tribeca will place a big order at the best ask price which is usually lower than the previous buy (as the market went a bid down because of the sell order).

The trade is filled and the market goes back to its original position, resulting in a loss for me.

I'm very sorry but can you roll back this update, or put it as an "APR Hardcore" option ?

I don't know if you have had time to try it and came to the same conclusion.

It's unfortunate that the theory doesn't join the practice on this one :s

**Comment by ctubio** [comment]
i run in aggressive always mode with long ping, i mean this modification didnt affect me so didnt noticed any change, but i agree the APR option should be a selector of 2 option (APR size | APR size and width), will make it so soon! (i think APR size and width is what you mean by hardcore :P then APR size is just the normal apr that doesnt affects pongAt)
