### ISSUE TITLE
Zombie quote status is used to calculate the difference with live quote status, generating negative values everywhere.

### ISSUE THREAD

**Issue by ctubio** [ctubio/tribeca#19]
goto https://github.com/ctubio/tribeca/issues/15#issuecomment-278263760

**Comment by Camille92** [comment]
[moved to [#22](https://github.com/ctubio/tribeca/issues/22)]

**Comment by ctubio** [comment]
meanwhile a quick fix is to click the cancel button for this orders in the UI, but will try to investigate this soon'¡

**Comment by Camille92** [comment]
Ahah it did not work for me. But true it is not an important issue.

I'm investigating what's happening with OkCoin (I can't really explain what's happening but it's weird), come back to you soon!
