### ISSUE TITLE
ag-grids are too heavy on loading if render too much initial data

### ISSUE THREAD

**Issue by ctubio** [ctubio/tribeca#20]
reported on IRC by ekienmeier; the solution may be to improve (more) the 3 implementations of ag-grid, or to simply trash them. when happens, the websocket dies with Not Connected msg, even if the connection is still alive.

another solution may be to relax the websocket healthcheck.

another solution may be to fire the websocket only after page loads.

**Comment by ekienmeier** [comment]
I'm currently running tribeca with commit ea8322653398c7de4be888d6962f5cb05e7ade98 which requires a click on the ag-grid of both market trades and filled order list to see their respective content. This works OK-ish for now.

When clicking on the ag-grid of the market trades, the webpage freezes for a few seconds (CPU usage goes up, etc.) and then the trades of the last 20 minutes are displayed.

I think this behaviour could be the solution for the filled order list: after clicking on the ag-grid, the filled orders of the last 20 minutes (or maybe even 60 minutes) are loaded and displayed. This will only cause a short pause without interrupting the websocket connection and forcing tribeca into the "Not connected" loop.

Maybe the reduction of data as described above is enough to display the market trades and filled orders without having to click on them first?
