### ISSUE TITLE
(ERRATUM EDIT) Bug OkCoin

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#21]
Hello Carles,

After running some tests (and discovered the git reset function). I identified a bug in the last OkCoin fix: cancel already filled orders https://github.com/ctubio/tribeca/commit/f6835a73ba9cf8f0f2234cbbbb25d36e61b8ad1f
Although the stability is perfect, here is what happens:

_Trades are not updated
_ width or bullet is not respected
_ (and that's the weird part) : The order in tribeca is not the same than on the market. (this happen again if the trade is manually cancelled). The orders can even be from the other side.
_ And at some point, tribeca will just stop trading!

It's crazy the affect that two lines can have!

What Tribeca thinks it's doing:
![capture d ecran 2017-02-09 a 14 05 05](https://cloud.githubusercontent.com/assets/6861590/22784602/f75922c6-eed0-11e6-8c1d-de39f0566313.png)

What is really happening:
![capture d ecran 2017-02-09 a 14 05 15](https://cloud.githubusercontent.com/assets/6861590/22784624/1e962316-eed1-11e6-8f82-181b868d71fb.png)

**Comment by Camille92** [comment]
The same things happened to me while running the version without the last fix.

An explanation could be that the problem existed before the fix, but was less obvious as the problem is temporary fixed by a reboot of tribeca.
With the improved stability of the last fix, the problem is more apparent!

**Comment by ctubio** [comment]
i didnt experienced this yet, or i didnt noticed it, but i will look carefully since now on to detect this

**Comment by Camille92** [comment]
I've been running some test and checking different versions:
I'm currently running tribeca of this date (very stable version) https://github.com/ctubio/tribeca/commit/b9639e82dab94e403614751e96ba46263df6b2d9

What I can say:
All versions stop the trading at some point, and experience more or less the same issues.

Only the versions after https://github.com/ctubio/tribeca/commit/f6835a73ba9cf8f0f2234cbbbb25d36e61b8ad1f  
show a difference between the webUI and what is sent to the market. It happens to all version.

Also it appears to happen more quickly than in the version I'm running.

One possible explanation is that OkCoin limits the number of trade sent to the market.
As I'm using quite a low width no EWMA I'm sending a lot of trade to the market (over 1000 a minute during high period). I might reach this limit and be blocked by Ok?
I'm going to ask them tomorrow if they have a limit.

But what is weird and not logical with this explanation is that when I restart tribeca it works perfectly again for some time.


It feels like issues with OkCoin are endless ! :/

I've asked the question to OkCoin about the trade limit. I should have an answer soon.

**Comment by ctubio** [comment]
ok so two issues here:
first, the different prices in tribeca related to the exchange is intentional, see:
https://github.com/ctubio/tribeca/blob/master/src/server/gateways/okcoin.ts#L455-L456
https://github.com/ctubio/tribeca/blob/master/src/server/broker.ts#L372-L374
looking at https://www.okcoin.com/fees.html, seems like the make fee is 0, no? should we change it in the code?

then i think the other problem of OkCoin is the 3000 request limit each 5min; we can avoid this by waiting 100ms between each request.. will try to implement soon (i already try it but still didnt found how to nicely do it :P)

you can read about the limit at https://www.okcoin.com/about/rest_faq.html

**Comment by Camille92** [comment]
Hey thank you for your comment.

The fee is 0 indeed and your explanation makes a lot of sense. But it was not happening before (version pre f6835a7)  And I don't see how it justifies to place bid trade when tribeca says it should be ask (or vice versa). So I stil believe there is a bug somewhere :p !


The 100ms is a good idea. But the market info is still updated. Does tribeca get in from another source ?

**Comment by ctubio** [comment]
well is OkCoin itself providing different sources (have 4 or 5 different channels, we are just banned from the new orders channel and/or the cancel order channel, at least in my long runs i always get banned from cancel orders :P)

**Comment by ctubio** [comment]
Can you please confirm what is the maker fee in OkCoin CN?, im not understanding very well https://www.okcoin.cn/fees.html

Related to https://www.okcoin.com/fees.html, since the maker fee is 0, i will update the codew, but i will not like to mess with CN, maybe can you help me to know what is the maker fee for CN?

Thanks'¡

**Comment by Camille92** [comment]
CN just changed its policy a week or 2 ago because of PBOC pressure.

It is now 0.2 flat!

**Comment by Camille92** [comment]
I'm still sure that there is a bug somewhere is the last updates.

Running the last versions tribeca does barely a trade an hour.
The difference between what tribeca shows and what is sent to the market is well above a fee
And the quotes are not updated!

I rerolled on my branch the last up of okcoin.ts, I'm going to re-implement one by one the updates to find exactly where is the error.
I send you a pull when I find it!

List of trade made by Tribeca this afternoon:
![capture d ecran 2017-02-10 a 18 47 02](https://cloud.githubusercontent.com/assets/6861590/22837557/7b2b8dd2-efc1-11e6-8e7f-cc871313dbf1.png)

**Comment by ctubio** [comment]
just saying, a niiice tool to go for each commit is https://git-scm.com/docs/git-bisect#_basic_bisect_commands_start_bad_good

**Comment by Camille92** [comment]
Hello, thanks for the tool!

I'll try to use next time, I've used a good old pen and paper for this one ahah and noted what happened.

So the error is there l108 of the okcoin.ts: ignoring error 10001.
`msg.errorcode == '10001'`

This is this line that provokes the errors I was talking about (tribeca not showing the same numbers in the webUI and what is sent to OkCoin, stop trading etc...).
You just need to remove the line and it's all cool.

Errors 10001 even if they are the most frequent are not causing crashes most of the time, so it doesn't change that much the stability.
The only noted issue is that Tribeca can crash when updating the settings.
A way to avoid that is to stop trading, update the settings and restart trading.

I've been doing some testing with ignoring, 10005, 10009 and both.
There is no bug apart from a few zombie order when using both. It doesn't affect the core functions of tribeca and I think you fixed it in later versions.

Obviously tribeca is more stable when both are ignored!

Happy trading :)

**Comment by Camille92** [comment]
Of course this is not perfect in term of stability but at least there is no bug!

**Comment by ctubio** [comment]
Awesome! many thanks :D

**Comment by ctubio** [comment]
Reopened because for me now crashes like in https://github.com/ctubio/tribeca/issues/15#issuecomment-277887907, will try to fix but whout ignoring 10001 :P

**Comment by Camille92** [comment]
yes I couldn't figure out how to to better.

Maybe ignoring 10001 on certain condition ?

But at least it never stops! :)

**Comment by Camille92** [comment]
It seems to be more stable when I don't look at the UI.

**Comment by Camille92** [comment]
fixed with #24
