### ISSUE TITLE
(IMPROVEMENT) Auto managing size of order

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#25]
Hi there!

Over the past few months thanks to the great work of @ctubio tribeca has now a lot of new wonderful features in term of strategies and general handling!

I'm thinking that now it can be time to improve it in term of managing the size of the orders. Here are two ideas that could boost tribeca's performances.

1) Profiting from "Super opportunities":

During big moves you can often see very wide width of 0.8% or even 1%. I believe tribeca should take advantage of those moments by:
_ Augmenting the trade / sec ratio
_ Augmenting the size of the bid and ask orders.

This could be done by for instance a rule stating:
If "market width > 3x set width" then Orders are twice as large and trade per sec is doubled.

2) Adapting order size to the evolution of the market:

Tribeca has two ways to make money.
The main one by doing market making and selling and buying at the same time.
The second one by following the market with the EWMA 100 / 200 crossing strategy (apMode Ewma Basic).

During flat time and moderate evolution of the price, the first strategy is the most profitable.
However during strong movements, it is often more interesting to be out of the market and enjoy the ride, or at least reduce our exposition.

That's why I believe is:
_ Bid and ask orders should be bigger during flat time (Target = 0)
_ bid orders should be bigger and ask smaller when the price goes up (Target = 1)
_ Ask orders should be bigger and bid orders smaller when price goes down (Target = -1) 

This could all be calculated thanks to the target value already calculated to define tbp.
And idea would be:
Bid size order = Bidsize(chosen by user) * (target + 2)
Ask size order = Asksize(chosen by user) * (2 - target)

So for instance if target = 1 (meaning the market is strongly going up):
Bid size = 3* the one chosen by user
Ask size = The size chosen by user

Target = 0.5 (moderately going up):
Bid size = 2.5 * the size chosen by user
Ask size = 1.5* the size chosen by user 

If target = 0 (calm market):
Bid size = 2* the one chosen by user
Ask size = 2* the one chosen by user

Etc..

Tell me what you think,

Camille

**Comment by ctubio** [comment]
About point 1:
it should *double the size in both sides or also only in one? (what options if also only one to decide which one?)

about double the trades/sec is not possible cos tribeca goes already as fast as possible i think (its only limited by its own existent orders where 0.01 of difference is the trigger to cancel current and place new).

*double could be instead a customizable value.

About point 2:
should be also possible to configure if the bids and asks are bigger or smaller depending if market goes up or down? or always bigger bids smaller asks on market up and smaller bids bigger asks on market down?

anyway will try to fully understand ewma and think about all the minimum possible customizable options to implement your idea before start with it :D

thanks'¡

**Comment by Camille92** [comment]
Hey Carles,

For the number 1, I think it should be both sides and for the trades/sec I'm talking about the one we configure in the settings :) I don't know if it's very clear.

But basically being able to have bigger orders when there is a "super opportunity" is what we need, I don't think having a higher rate would make it better.


For the second point, the more I think about it, the more it seems complicated for something that might not be better than what we have now.

Talking about upgrades, with the rise of all alts, I think adapting tribeca to work for more crypto /exchanges is the best effort to potential benefit ratio we can find.

And thinking about new strategies instead of EWMA basic! :)

I can explain you the EWMA when you want!

**Comment by ctubio** [comment]
1st point clear thanks'¡ so you mean to double `trds` value and leave `/sec` as user defined?

2nd neat! and thanks again'¡ (my plan is to rereread your [previous post](https://github.com/ctubio/tribeca/issues/7) about it)

btw i dont have suggestions for new exchanges (what i would like to do is to support more than one exchange in the same single application); but if you have suggestions for new exchanges feel free to create a new issue for each'¡ (i don't promise any in advance cos is lot of work xD)

**Comment by ctubio** [comment]
@Camille92 said at #28: For SOP I think it's a very good idea to double (or triple) the size of the orders as well if APR is off!
