### ISSUE TITLE
Allow different width for Pings and Pongs

### ISSUE THREAD

**Issue by ctubio** [ctubio/tribeca#27]
Currently the ```width``` is applied to the margin for new orders related to the fair falue, and also for pongs related to the matching ping.

Would be great if the margin from the fair value for new orders and the margin from the ping for pongs are  2 different customizable values.

**Comment by ctubio** [comment]
![aee4b7856cdf28a89a3bcf3308a72c47](https://cloud.githubusercontent.com/assets/1634027/24838200/a2fff7d0-1d43-11e7-9df2-739dffee838e.jpg)

**Comment by Camille92** [comment]
hahah I was thinking a few weeks back that it would be a great feature!

You're awesome!

Ps: I send you the 'prize' for fixing OkCoin api as soon as I get out of my LTC position! :)
