### ISSUE TITLE
LIST IMPROVEMENTS:

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#28]
Dear Carles and all,

Here is a list of all the improvements I can think of for Tribeca I think it's more convenient that way but I can do one issue for each idea if you want.

**1) Safeties**

The goal of this safety is to be protected by sudden rise or drops in the price. It works with a simple formula: If x% drop (or rise) in y minutes : market sell (or buy) your position + change TBP to 0 (or 1).

Example: If I set the limit to be 2% in 5 minutes if the price moves up by those number, I market buy to enjoy the ride.

Target base position has to be changed when the safety is triggered so that tribeca doesn't start to sell and/or activate APR right after buying.
The difficult part is to find a trigger for when to start to reuse normal APR instead of the "safety" one.
I have two ideas for that the first one is to switch back to normal when EWMA 100 starts ro rise (or go down). The second one is to use a timer counting to 10 or 20 minutes.

**2) Trading new pairs:**

If you use ewmabasic, this setting will greatly improve tribeca's ROI because now if BTC goes down there is nothing to do and noway of making money.
I give you an example with GDAX for Europeans. We have access to 3 markets there:
BTC EUR, LTC BTC, ETH BTC.
By having 2 or 3 tribeca's running on the exchange instead of one and with correctly set pdiv, the funds will move 'automatically' to where you can make most money.
Example: BTC is going sideways and LTC up:
In this configuration, tribeca will try to be half fiat half btc on the BTC EUR market and try to be 100 ltc on the LTC BTC market.
It will use the BTC left to buy LTC so we can enjoy the ride!

In a second time we can imagine one tribeca being able to manage all those market at once, this would allow for a better management of the funds from one pair to another, but it is imho a LOT more work, so better going little by little.

**3) Changing Bid Size, Ask Size and Pdiv in % of the funds:**

This is necessary if we want to run different Tribeca on one exchange efficiently.
If we don't do it we will for sure have to big or too small orders in all the pairs in comparison of the available funds.

**4) Addind new exchanges:**

Bitfinex, Kraken or exchanges with a maker taker fee and 0 fee for us.
However, this is imho less important that the 3 first points for now :)

I hope it makes sense for you as well! Tell me what you think :)
I really believe having tribeca on different pairs will make a HUGE difference !

Ps: For SOP I think it's a very good idea to double (or triple) the size of the orders as well if APR is off!

**Comment by ctubio** [comment]
1) Moved to #32.
2) Moved to #31.
3) Moved to #30.
4) Moved to #29.
SOP comment Moved to #25.

Many many thanks for sharing your ideas'¡
