### ISSUE TITLE
Add new exchanges

### ISSUE THREAD

**Issue by ctubio** [ctubio/tribeca#29]
@Camille92 said at #28:

Bitfinex, Kraken or exchanges with a maker taker fee and 0 fee for us.

**Comment by ctubio** [comment]
I will attempt to replace the custom integration with the current exchanges with npm libraries maintainted by other people, so we can make use of more exchanges easily. Otherwise will need to code from scratch the new integrations.

**Comment by Camille92** [comment]
Yes I've seen some libraries with data from a lot of exchanges! :)

**Comment by ctubio** [comment]
Closing because is already listed in the [TODO](https://github.com/ctubio/tribeca/blob/master/TODO) file.
