### ISSUE TITLE
Changing Bid Size, Ask Size and Pdiv in % of the funds

### ISSUE THREAD

**Issue by ctubio** [ctubio/tribeca#30]
@Camille92 said at #28:

This is necessary if we want to run different Tribeca on one exchange efficiently.
If we don't do it we will for sure have to big or too small orders in all the pairs in comparison of the available funds.

**Comment by ctubio** [comment]
about pDiv i have no idea how to do it, but for the other two sizes we can do it with a rule of 3, taking all funds (held + available) in both sides as 100%, and funds in the give side as x% (so this is calculated 2 times, one for each side), then the subject of the conversion could be the bid/ask sizes based on user defined values for this sizes as 100%.

in other words, user defined values for bid/ask sizes will be taken as maximums, and the % of funds in the given side will decrement it accordingly.

for example, if we have ฿100 in base funds (available + held in ask side) and 200€ in quote funds (available + held in bid side), in case that this option is enabled, the sizes will be:
Bid Size = user_value / 100 * (100 * quote_funds / ((base_funds * fair_price) + quote_funds))
Ask Size = user_value / 100 * (100 * base_funds / (base_funds + (quote_funds / fair_price)))

this could be enabled with a simple checkbox, denoted by a "max" prefix in the label of the bid/ask size inputs once enabled.

aboud pDiv, im not sure how to do it :sob:

**Comment by Camille92** [comment]
Hey I don't understand why it is a maximum ?

I was thinking about using the total funds value that we can find on the left or Tribeca for ease.

Don't you think it can do the trick ?

So if we just use the total BTC value found on the left, we have the same equation for the 3 variables:

(uservalue*totalbtc)/100


So if we have a total of 5btc, 50% in fiat and 50% in BTC and we have a Bid and ask setting of 10% and pdiv of 10 as well get:

10*5 /100 = 0.5 btc orders to be sent to the market and used for pdiv.

If 2 of those Btc are now not available (because held in eth for instance) with the same settings orders will now be:
10*3 /100 = 0.3 !

**Comment by ctubio** [comment]
So still one single checkbox to enable/disable this feature, and when enabled, the value of the inputs in bidSz, askSz and pDiv is a percentage instead of an absolute value.

The percentage is then based on the total available for each side, where 100% is the total available and the x% is each user defined value.

Then:
bidSz = user_value * (fiat_funds / fair_price) / 100
askSz = user_value * btc_funds / 100
pDiv when applied to bid side = user_value * (fiat_funds / fair_price) / 100
pDiv when applied to ask side = user_value * btc_funds / 100

Could be denoted  by adding the suffix "%" to the labels of the affected fields.

Please let me know if this is what you mean'¡ (thanks'¡)

**Comment by Camille92** [comment]
It's nearly that,

We have to take the total funds to calculate the % so total of the fiat and btc each time. If we use your formula we would end up pushing artificially the btc to fiat ratio at around 50%.

So correct formula is more:
BidSz = AskSz = pDiv = user_value * total_funds_in_btc /100
total_funds_in_btc = (fiat_funds / fair_price) + btc_funds

**Comment by Camille92** [comment]
I don't know if it would use a lot of ressources, but it doesn't need to be done all the time, maybe once per minute or 2 minute :)

**Comment by ctubio** [comment]
ok i see, so is like my first formula but using as 100% the total funds instead of the user inpus. User inputs are then the x% used instead of the 100%.

got it'¡!
BidSz = AskSz = pDiv = user_value * total_funds / 100
where total_funds = (fiat_funds / fair_price) + btc_funds

awesome!

**Comment by Camille92** [comment]
Ohh I got the goal of your first formula now! :)

Yes exactly !
