### ISSUE TITLE
Trading new pairs

### ISSUE THREAD

**Issue by ctubio** [ctubio/tribeca#31]
@Camille92 said at #28:

If you use ewmabasic, this setting will greatly improve tribeca's ROI because now if BTC goes down there is nothing to do and noway of making money.
I give you an example with GDAX for Europeans. We have access to 3 markets there:
BTC EUR, LTC BTC, ETH BTC.
By having 2 or 3 tribeca's running on the exchange instead of one and with correctly set pdiv, the funds will move 'automatically' to where you can make most money.
Example: BTC is going sideways and LTC up:
In this configuration, tribeca will try to be half fiat half btc on the BTC EUR market and try to be 100 ltc on the LTC BTC market.
It will use the BTC left to buy LTC so we can enjoy the ride!

In a second time we can imagine one tribeca being able to manage all those market at once, this would allow for a better management of the funds from one pair to another, but it is imho a LOT more work, so better going little by little.

**Comment by ctubio** [comment]
Here the suggestion is only to support more curerncies in gdax and in okcoin, right?

**Comment by Camille92** [comment]
I don't use other exchanges for now, so as far as I need it yes but any exchange is good! :)

**Comment by Camille92** [comment]
When I see charts like that, I know tribeca would do so great on that!

No a day without a +10 or minus 10% :)

https://www.tradingview.com/x/kHV7oI6B/

**Comment by ctubio** [comment]
Closing cos I think this is resolved since your #38.
