### ISSUE TITLE
Support multiple exchanges in the same app

### ISSUE THREAD

**Issue by ctubio** [ctubio/tribeca#34]
once a single app works with multiple exchanges, support https://github.com/ctubio/blackbird somehow

**Comment by Camille92** [comment]
(Arbitrage can be done within the same exchange as well :) )
![arbitrage-bot-overview1](https://cloud.githubusercontent.com/assets/6861590/24973633/c7a3d970-1fbf-11e7-8b90-f3870031aec1.png)

Image from haasonline

**Comment by ctubio** [comment]
Closing because is already listed in the [TODO](https://github.com/ctubio/tribeca/blob/master/TODO) file.
