### ISSUE TITLE
Bitfinex reports too big account value

### ISSUE THREAD

**Issue by viperzero** [ctubio/tribeca#48]
Bitfinex seems to report nearly twice the account value and trades report not enough money to complete.
---
```
app exchange: Bitfinex/BTC/USD
app version: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
im sorry i dont currently own any Bitfinex account

~let me free some funds and create a Bitfinex account for testing during the next weekend(s)~

looking at https://www.bitfinex.com/fees, i see Bitfinex have maker fees, so im really not interested into support Bitfinex (they are already supporting themselves very well); anyway if anybody wanna support Bitfinex, please open a new issue referencing this (issue #48) and send 0.02 BTC to my git tip address (see my profile or any commit message) and i will dedicate time to fix any current issue with Bitfinex gateway in tribeca using that 0.02 BTC to test it (later i will remove the funds from Bitfinex to stop supporting them, and maaaaybe buy some chocolate milk).

Also another solution is to request this fix to the upstream project [michaelgrosner/tribeca](https://github.com/michaelgrosner/tribeca).

Many thanks for your time viperzero'¡
