### ISSUE TITLE
Improve labels

### ISSUE THREAD

**Issue by ekienmeier** [ctubio/tribeca#56]
Now that other trading pairs are possible (woohoo!), I think adding some info to the labels in the "Settings" section could help a lot:
1. Remove misleading tooltips. For example, tbp, pDiv, and others have a tooltip telling you to enter a valid value, if you enter floating point values. However, the floating point values are perfectly valid and work just fine.

1. Add the currency to the label, so it becomes clear which currency is used for this particular setting. For example, width, pingWidth, and pongWidth values refer to the first currency of a pair (so for EUR/BTC it's EUR), however tbp and pDiv refer to the second currency (in this case BTC). I had a hard time wrapping my brain around these values when setting up ETH/BTC and LTC/BTC on GDAX. So what I am proposing is adding the actual currency to the label: width (EUR), tbp (BTC), etc.

**Comment by ctubio** [comment]
agree with 2nd point'¡

about 1st point, what tooltips you mean? im not sure that i ever saw any tooltip in my form; maybe can you make a screenshot for reference?

many thanks'¡

**Comment by ekienmeier** [comment]
Here you go:

![image](https://cloud.githubusercontent.com/assets/24856849/25641020/4b718432-2f92-11e7-80bb-f5c47d451337.png)

Mouse is hovering over the input field of bidSize in this case.

**Comment by ctubio** [comment]
oh, that may be some funky html5 feature of number inputs, can you please let me know what SO, browser name and version are you using? (here i dont see any tooltip in Chrome 57 under winy 7)

thanks'¡

**Comment by ekienmeier** [comment]
You are correct - these inputs have their type set to "number" without specifying a "step" attribute. Found more info [here](http://stackoverflow.com/questions/19011861/is-there-a-float-input-type-in-html5). Maybe we should use a step value of 0.00001? Also, setting a "min" value could also prove useful. What do you think?

**Comment by ctubio** [comment]
will try to make use of `min` and `max` attributes and display the currency symbols of each numeric input, many thanks for the research'¡

**Comment by ctubio** [comment]
i still cannot see any tooltip, but in theory... we may had improved something? (still missing the currency symbols somewhere)

let me know in case it was better before, so we can rollback please xD

**Comment by ekienmeier** [comment]
Much better now, the increment/decrement using arrow up/down work fine now too. Thanks for that!

The only field missing is the trades/sec field:
![image](https://cloud.githubusercontent.com/assets/24856849/25680462/35475898-3051-11e7-96b1-fabc6c8beec2.png)

As you can see, any floating point number is still marked as invalid - however, Tribeca works just fine with, for example, 1.5 trades per x seconds.

I do like the highlighted border pointing out invalid values. 👍

**Comment by ekienmeier** [comment]
Another thing I came across when setting up ETH/BTC and LTC/BTC:
The value information does not display the currencies, so I have to guess which currency is associated with which value:

![image](https://cloud.githubusercontent.com/assets/24856849/25680876/9bf039d8-3052-11e7-980b-27753d5071cc.png)

For EUR/BTC the distiction is quite easy, but for LTC/BTC and ETH/BTC it's not - well, at least not at first. :)

I still run an older version of Tribeca for the EUR/BTC pair (commit ea83226) which still has the Bitcoin and Euros symbols. The symbols make the info really easy to read, just one glance gives you everything you need to know from that box. Maybe use that kind of layout as a template?

**Comment by ctubio** [comment]
Hello ekienmeier'¡
im afraid to put the symbol near the waller values because there isnt much free space horizontaly (before we had less decimals but now we have up to 8), hope you agree with the solution in the latest commit'¡

(also note, when hover the mouse on wallet values, it should show a tooltip with the currency symbol and the total/available/held)

((still missing the currency symbols somewhere near the inputs))

**Comment by ekienmeier** [comment]
I like the tooltips
Just had an idea - the headline of the wallet info with the exchange name states, for example, LTC/BTC. Underneath it we see the values for the 2nd currency (BTC), then the values for the 1st (LTC). And then there's the total value information: 1st currency on top (LTC), underneath the 2nd currency (BTC).

We could try to swap the currencies in the middle (so, LTC and BTC, instead of BTC and LTC), something like that (mock-up):
![image](https://cloud.githubusercontent.com/assets/24856849/25682949/60ea7634-305a-11e7-94e0-b2f1f13add34.png)

What do you think?

**Comment by ctubio** [comment]
neat! you read my mind! (or i read your comment, not sure xD)

**Comment by ekienmeier** [comment]
The wallet looks very good now IMHO, it's well structured. I would like to hear feedback from others on this.

While we're at it: the "Market Width" and "Quote Width" numbers could use a few more decimal places (5 instead of 2) ;)

![image](https://cloud.githubusercontent.com/assets/24856849/25684955/a202ed04-3064-11e7-8601-aae7c18353b1.png)

**Comment by ctubio** [comment]
sorry again! i added the currency unit to the numeric inputs, but i still cannot see nothing yet (no arrows no tooltip, and also no unit for me); do you see the unit in the numeric inputs? if so, is OK?
many thanks'¡

the plan was to do something like http://stackoverflow.com/questions/28605416/display-of-units-in-html-stepper-input-type-number, but in this page i can see all OK but not in tribeca :( donno why you can; are you using chrome?

if you think that the last commit is useless, maybe we can implement http://jqueryui.com/spinner/#currency to fix this, as you consider

**Comment by ekienmeier** [comment]
You are right, the unit attribute is ignored and no symbols are shown in the input fields. Looking at [this article](https://www.w3schools.com/html/html_form_attributes.asp), this behaviour is to be expected as "unit" doesn't seem to be a valid attribute for input.

Replacing the "unit" attribute with the "title" attribute would give us a tooltip with the currency used, which would be OK for desktop browsers (not sure about mobile browsers with touch interface). I think this is worth a try.

I also thought about the "placeholder" attribute, but this only shows information when the input field is empty, which in Tribeca is hardly ever the case. So this isn't really practical.

The arrows in the number input fields don't appear for me either. I tried it in Chrome (57) and Edge, both on Windows 10 (version 1703). But I don't really miss them because it's faster to just type the numbers anyway.

Another thing I noticed: since both "Market Width" and "Quote Width" now show more decimal places (excellent, thanks for that!), there's a line break with the "Wallet TBP" and its value:
![image](https://cloud.githubusercontent.com/assets/24856849/25735048/b5b73a80-3168-11e7-8f77-3bf839fedec8.png)

This could be fixed by using abbreviations for Market (Mkt), Quote (Qte), and Width (W):
![image](https://cloud.githubusercontent.com/assets/24856849/25735084/ec3c8a1a-3168-11e7-9264-37426955bde0.png)
(see [market](http://www.abbreviations.com/abbreviation/market), [quote](http://www.abbreviations.com/abbreviation/quote), and [width](http://www.abbreviations.com/abbreviation/width))

What do you think?

**Comment by ekienmeier** [comment]
> if you think that the last commit is useless, maybe we can implement http://jqueryui.com/spinner/#currency to fix this, as you consider

While this solution seems quite elegant, I'm not sure if it's worth the effort. I'd be quite happy with a tooltip on the input fields showing the currency. :)

**Comment by ctubio** [comment]
im sorry i failed with the position/white-space/overflow of the TBP, will fix without abbrebviations'¡ :D

cool! lets go for the title attribute then'¡! i didnt wanted to use it in first place to not replace the title of the html5 saying the min/max values, but is more important to see the unit than the html5 tooltip so lets replace the titles'¡

thanks for your time'¡!

**Comment by ctubio** [comment]
btw i was finally able to see in tribeca this html5 funky features (using Firefox), and they look quite horrible this gray buttons everywhere xD

**Comment by ekienmeier** [comment]
Cool, line break is fixed now, thanks a lot! 🖖
