### ISSUE TITLE
Include Cryptowatch Embed

### ISSUE THREAD

**Issue by ekienmeier** [ctubio/tribeca#62]
[Cryptowatch](https://cryptowat.ch) offers a [library](https://github.com/cryptowatch/embed) to include their charts in websites.

I think it would be very useful to see the charts of the exchange and currency pair that Tribeca is running on within Tribeca's page. Maybe underneath the ping/pong history, and hideable just like the stats, automatically resizing to fill the empty space there?

Here's a simple mock-up:
![image](https://cloud.githubusercontent.com/assets/24856849/25746982/1c0bc1e2-31a6-11e7-8780-0f3978462a77.png)

Please let me know what you think. 😄

**Comment by ctubio** [comment]
now thats a happy idea'¡!

let me discover cryptowatch and inject it into our app somehow niiiiiiicely; if we end up also replacing the horrible market data table (the one at the very right side), then we can be double happy'¡

many many thanks for the links/mockup'¡!'¡

**Comment by ctubio** [comment]
:sunflower: ima leave this here: https://jsfiddle.net/s2k0ahf1/1/

**Comment by ekienmeier** [comment]
I didn't have much time recently to check the features in newer versions, but I saw the cryptowatch charts and I like them a lot. Thanks for including them, really appreciate it! 👍
