### ISSUE TITLE
Old Orders still showing in the ui

### ISSUE THREAD

**Issue by beegmon** [ctubio/tribeca#69]
After the latest npm diff pull I started noticing orders getting stuck in the ui. 

They don't appear to be getting stuck on the exchange, but the UI is showing old orders, that have either been canceled previously, or have been filled. They are present both in the mrkt list display and the live order list. 

When hitting cancel on the old order, the order appears to go-away, along with the highlighted box in the mrkt list, but returns a could of seconds later. Both in the mrkt list and the live order list.

No amount of clicking cancel orders, or clicking cancel on the individual problem order appears to get the old order to clear. The width also shows a negative number when these old orders get stuck.

This doesn't appear to affect actual quoting at least as far as I can tell at the moment.

**Comment by ctubio** [comment]
im sorry yesterday fixed bitfinex but broke okcoin, and today fixed okcoin but broke coinbase.

will try to fix coinbase asap'¡ (let me know if you issue is with another exchange diff than coinbase)

sorry again'¡

**Comment by beegmon** [comment]
No worries glad it's at least on the radar. I only trade on gdax (coinbase) so I will hold on while this get resolved.

Thanks!
