### ISSUE TITLE
Bug: Tribeca doesn't see some orders in market book (Coinbase)

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#76]
Hello!

I'm still working on finding what's wrong with Tribeca but what I've found is that it doesn't see some orders in the market so it does not respect width.

Here is an example:
![capture d ecran 2017-05-12 a 13 11 39](https://cloud.githubusercontent.com/assets/6861590/25995908/c9332fc2-3714-11e7-9e4a-fa8ab4d2011b.png)
![capture d ecran 2017-05-12 a 13 11 29](https://cloud.githubusercontent.com/assets/6861590/25995912/cf5ed4be-3714-11e7-8b4d-da0cf9360372.png)

There two orders close from market price at 1673 and 1676.02 don't appear on Tribeca :/

And AK-47 still doesn't work!

**Comment by Camille92** [comment]
Fixed https://github.com/ctubio/tribeca/pull/77

**Comment by ctubio** [comment]
market data integration in super simple, no way is missing data; if is missing data, is because really is not receiving this data from the gateway.

**Comment by ctubio** [comment]
coinbase has definitely some issue with market data; (before mess it more, lets check that we are up to date with https://github.com/coinbase/gdax-node)

**Comment by ctubio** [comment]
that was some messed up integration xD amazing that we survived with it till now

so happy with the results of integrating directly the official gdax api, can't belive the amount of :hankey: we had been running before https://github.com/ctubio/tribeca/commit/22993223ef2b391ce9724f0b5209094cb5fca075 xD lets keep a close eye to it cos is all new the gdax integration now (but it works like a swiss clock i may say xD)
