### ISSUE TITLE
Bug OkCoin: Ghost orders stay in orderbook

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#80]
Hi Carles,

Some ghost orders stay in the order book and mess with the width and everything (ewma calculation and all).

I can't cancel the order in Tribeca, it reappears!

Tell me if you need more details
![capture d ecran 2017-05-14 a 12 53 25](https://cloud.githubusercontent.com/assets/6861590/26033121/8164bc2e-38a4-11e7-894b-35c014b63ce9.png)

**Comment by ctubio** [comment]
im sorry i try super hard but there is not way im abgle to reproduce this,
for me OkCoin cancels works super niiiiice.

**Comment by Camille92** [comment]
are you free on irc ?

**Comment by Camille92** [comment]
APR BUG:
![capture d ecran 2017-05-14 a 14 36 49](https://cloud.githubusercontent.com/assets/6861590/26033800/de9d695a-38b2-11e7-9d08-fe45df9c486b.png)

**Comment by ctubio** [comment]
.:2823analpaper19:. ok so the problem with APR, is that it doesnt cancel orders if is an order active in a side that is not expected to place orders
19.:2823analpaper19:. so when APR is on and active orders are in side Buy, it will not cancel orders in side Sell
19.:2823analpaper19:. cos is only working in Buy side, and doesn't care whats going on on Sell side (and happens to be an avtive order)
28.:192420Camille9228:. Yepp

**Comment by Camille92** [comment]
Hello !

I have some news for this issue so the so called: "APR BUG" is fixed but the issue "Immortal Zombies orders" come back after a few time running.

It makes the web UI practically unusable after a few hours of running both for LTC and BTC.

However:
The bot still send and cancel orders.

I think it has an effect on Ewma basic but I'm not sure.

Can you please reopen ?
![capture d ecran 2017-05-15 a 10 30 08](https://cloud.githubusercontent.com/assets/6861590/26048985/adcfcb2c-3959-11e7-88e2-181064982bd9.png)

**Comment by ctubio** [comment]
in what echange and what mode it was? is OkCoin with AK-47?

**Comment by Camille92** [comment]
Yes it's OkCoin with AK-47, it doesn't happen in other exchanges!

Maybe I'll switch to boomerang if it protects me from that

**Comment by Camille92** [comment]
So after using boomerang for around a day, I can confirm that it only happens on OkCoin with Ak-47.

I switched to Boomerang to fix the issue :)

**Comment by Camille92** [comment]
I spoke too fast, they happen as well on Boomerang :s

**Comment by ctubio** [comment]
ok, today i experienced this also in OkCoin/Boomerang

**Comment by ctubio** [comment]
fixed at https://github.com/ctubio/tribeca/commit/2a49c9e491bd476544f7f780b519296480b8cd95
