### ISSUE TITLE
What is the BW Option?

### ISSUE THREAD

**Issue by beegmon** [ctubio/tribeca#81]
I just noticed it was added in the UI, but can't find anything in Docs

**Comment by ctubio** [comment]
the description was added to the MANAL recently, is:
`bw` - Enable Best Width to place orders avoiding "hollows" in the book, while accomodating new orders right near to existent orders in the book, without leaving "hollows" in between.

before best width was enabled always, but now can be disabled with a checkbox
hope it helps'¡

**Comment by beegmon** [comment]
Ah makes sense,  must have missed it when scanning through the manual..thanks!
