### ISSUE TITLE
Can not connect to OkCoin

### ISSUE THREAD

**Issue by viperzero** [ctubio/tribeca#85]
After upgrading to latest version I can not connect anymore to OkCoin. Web gui does load and it says:  Disconnected from exchange Can not connect through Okcoin button. Log is empty. Little clueless how to proceed.
```
app exchange: OkCoin/BTC/USD
app version: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
to see the log please run the app without forever, that is:
```
$ nodejs tribeca.js
```

cos now we only output the log messages to stdout, so we dont have a log file anymore

maybe can you copy here your error?
i know there is some situation where OkCoin fails to start, but this doesnt happens always so trying  to start it again may work.

let see if we both are experiencing the same error, or if yours is a new one, thanks for your help'¡

**Comment by ctubio** [comment]
are you running the latest commit? im not able to reproduce the error i was talking about anymore :(
please provide an error report so i can follow the bug, many thanks'¡

**Comment by viperzero** [comment]
This started to happen yesterday after I upgraded and now updated to latest commit. Here's the output,  seems heartbeat is lost:

{"name":"tribeca:gateway:OkCoinWebsocket","hostname":"ubuntu-512mb-toronto","pid":9018,"level":30,"msg":"OkCoin heartbeat lost.","time":"2017-05-17T18:15:53.247Z","v":0}
{"name":"stdev","hostname":"ubuntu-512mb-toronto","pid":9018,"level":30,"msg":"Unable to compute STDEV value","time":"2017-05-17T18:15:53.593Z","v":0}
{"name":"stdev","hostname":"ubuntu-512mb-toronto","pid":9018,"level":30,"msg":"Unable to compute STDEV value","time":"2017-05-17T18:15:54.593Z","v":0}
{"name":"stdev","hostname":"ubuntu-512mb-toronto","pid":9018,"level":30,"msg":"Unable to compute STDEV value","time":"2017-05-17T18:15:55.594Z","v":0}
{"name":"stdev","hostname":"ubuntu-512mb-toronto","pid":9018,"level":30,"msg":"Unable to compute STDEV value","time":"2017-05-17T18:15:56.594Z","v":0}
{"name":"stdev","hostname":"ubuntu-512mb-toronto","pid":9018,"level":30,"msg":"Unable to compute STDEV value","time":"2017-05-17T18:15:57.601Z","v":0}
^C{"name":"main","hostname":"ubuntu-512mb-toronto","pid":9018,"level":30,"msg":"Handling SIGINT","time":"2017-05-17T18:15:57.974Z","v":0}
{"name":"main","hostname":"ubuntu-512mb-toronto","pid":9018,"level":30,"msg":"All exiting event handlers have fired, exiting application.","time":"2017-05-17T18:15:57.985Z","v":0}
{"name":"main","hostname":"ubuntu-512mb-toronto","pid":9018,"level":30,"msg":"Exiting with code 0","time":"2017-05-17T18:15:57.988Z","v":0}

**Comment by viperzero** [comment]
Now after starting again with logging It started working alltough nothing changed, perhaps this is on the okcoin end issue?

{"name":"tribeca:gateway:OkCoinWebsocket","hostname":"ubuntu-512mb-toronto","pid":9076,"level":30,"msg":"Successfully connected to addChannel: ok_sub_spotusd_btc_depth_20","time":"2017-05-17T18:20:32.354Z","v":0}
{"name":"positionmanager","hostname":"ubuntu-512mb-toronto","pid":9076,"level":30,"msg":"recalculated target base position: 0","time":"2017-05-17T18:20:32.367Z","v":0}
{"name":"tribeca:gateway:OkCoinWebsocket","hostname":"ubuntu-512mb-toronto","pid":9076,"level":30,"msg":"Successfully connected to addChannel: ok_sub_spotusd_btc_trades","time":"2017-05-17T18:20:32.368Z","v":0}
{"name":"tribeca:gateway:OkCoinWebsocket","hostname":"ubuntu-512mb-toronto","pid":9076,"level":30,"msg":"Successfully connected to login","time":"2017-05-17T18:20:32.488Z","v":0}
{"name":"positionmanager","hostname":"ubuntu-512mb-toronto","pid":9076,"level":30,"msg":"recalculated target base position: 0.2155265","time":"2017-05-17T18:20:32.542Z","v":0}

**Comment by ctubio** [comment]
many thanks for the logs, will try to make the app to reconnect on heartbeat lost

**Comment by ctubio** [comment]
added reconnect at https://github.com/ctubio/tribeca/commit/2a49c9e491bd476544f7f780b519296480b8cd95

**Comment by viperzero** [comment]
Many thanks for the reconnect, will be testing the new version.
