### ISSUE TITLE
Ripple on Bitfinex!

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#87]
Hello Carles,

Bitfinex just added Ripple on the exchange. Can you please add them to the list of tradable markets!

XRP/BTC
XRP/USD

Ps: You should watch XRP is has been exploding in the past few weeks! I'm super happy we can trade it now!

**Comment by ctubio** [comment]
thank you'¡ fixed at https://github.com/ctubio/tribeca/commit/d30eb0724edaa671b711d3b555c74792bfd008b4
