### ISSUE TITLE
FairValue calculation error on OkCoin

### ISSUE THREAD

**Issue by viperzero** [ctubio/tribeca#89]
the fair value is counted wrong on OkCoin. I use the latest commit. currently the value is 2013 but somehow bot think it is over 2100 

![fairvalue_error](https://cloud.githubusercontent.com/assets/1883543/26279037/c76ee0b6-3db1-11e7-9c26-09d118067a1b.jpg)

**Comment by ctubio** [comment]
in the image i see it displays a the top bid of 2120, and the top ask of 2120.01, thats why it displays also a fair value of 2120.

from where you take the values of 2013 and 2100?
