### ISSUE TITLE
Implement BitMEX Gateway

### ISSUE THREAD

**Issue by strikeout** [ctubio/tribeca#91]
Implementing a BitMEX Gateway would be awsome!

Official WS Api  Connector:
>> https://github.com/BitMEX/api-connectors/tree/master/official-ws/nodejs

**Comment by ctubio** [comment]
looks like it have nice Maker fees (https://www.bitmex.com/app/fees)

**Comment by Camille92** [comment]
it's a future market but yes that will be interesting to try with the negative maker fee

**Comment by Camille92** [comment]
My bad don't forget they have a settlement fee of 0.05 as well. But it's still very low!

**Comment by ctubio** [comment]
~i dont have prior experience with future markets, but will wrap my head arround it some day~ like today

**Comment by ctubio** [comment]
```js
while (GitTip === 0) {
  try {
    new FeatureRequest();
  } catch() {
    throw new Exception('GTFO');
  }
}
```

**Comment by strikeout** [comment]
that was unnecessarily rude

**Comment by ctubio** [comment]
```
who | xargs killall
```

**Comment by ctubio** [comment]
![benderbendingrodriguez](https://user-images.githubusercontent.com/1634027/27196948-bbf1766c-520c-11e7-9819-fde7cb3ec2b9.jpg)
